category: web
points:   300
title:    Веб-департамент
author:   nsychev
description: |
    <p>Одна небезызвестная социальная сеть запустила веб-департамент. Ведущие специалисты будут искать неправдивую информацию в интернете — ссылки на неё в социальной сети разместить больше не выйдет. Теперь пользователи в безопасности!</p>
    <p>Однако, нам кажется, руководитель веб-департамента что-то скрывает. Мы нашли их служебный ресурс и даже QR-код одного из сотрудников для одноразовых кодов. Поможете немного освоиться в сети?</p>
    <p><em>Примечание.</em> Чтобы решить это задание, вам нужно авторизоваться как пользователь <code>admin</code>.</p>
    <p><em>Подсказка (добавлена в 17:43).</em> Локальная сеть сервера — /24 (x.y.z.1 — x.y.z.254). Осталось увидеть первые три числа.</p>
attachments_path: public/
generator:
    exec: kyzylborda-docker-generator Dockerfile.generator ./generate.py
    multi_generator_key: webdept
daemon:
    exec: kyzylborda-docker-compose-daemon
    cwd: app
    socket: ./webdept.sock
    socket_type: http
