category:  reverse
points:    300
title:     Термопринтер
author:    kalan
description:
    <p>Представьте, что вам подарили термопринтер Poooli L3 и вам нужно напечатать на нём вот эту картинку:</p>
    <p><img src="static/thermal-printme.png"></p>
    <p>Вам даже подсказали, где <a href="https://www.poooli.com/bla4sj-list.html">скачать драйвера</a>, и что драйвера для Мака как-то можно запустить под Линуксом.</p>
    <p>С помощью драйверов вам даже удалось распечатать слова <tt>Test... test... test...</tt>, но после этого всё почему-то перестало работать…</p>
attachments_path: attachments
generator: ./run_generator.sh
daemon:
    exec: kyzylborda-docker-compose-daemon
    cwd: app
    socket: ./thermal.sock
    socket_type: http
